import Head from 'next/head'
import Navbar from '../components/Navbar'
import Hero from '../sections/Hero'

export default function Home() {
  return (
    <div className='overflow-hidden h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
    </div>
  )
}
